### ISSUE TITLE
tried most of the values it keeps on say bad value 

### ISSUE THREAD

**Issue by Samirahajiragab** [Samirahajiragab/accessibility-fixer-upper#1]
<img width="506" alt="image" src="https://user-images.githubusercontent.com/55094325/79251453-2619df00-7e4e-11ea-9407-72c8357393d0.png">
@mackenzierose

**Comment by MacKenzieRose** [comment]
Role is a very specific term, which is why you're getting `bad value` errors.

Role is limited to only exact terms like: navigation, banner, contentinfo, main etc; we can't use things like "shrubs"

Cheers!
MacKenzie

**Comment by Samirahajiragab** [comment]
what are the good examples?

**Comment by MacKenzieRose** [comment]
Things like: `role="navigation"` `role="banner"`
